### ISSUE TITLE
Not working with default props on Styled components

### ISSUE THREAD

**Issue by tehandyb** [oliviertassinari/babel-plugin-react-remove-properties#60]
I have a react styled component that uses a default prop but the property is not getting removed. My standard react components are getting the property removed correctly. The code is like:
```
const MyComponent = styled.a`
color: green;
MyComponent.defaultProps = { 'data-test-id': 'my-component' };
```

**Comment by oliviertassinari** [comment]
@tehandyb I don't understand. What's the actual behavior? What's the expected behavior?
This plugin has nothing to do with the `defaultProps`. If you want to remove the attributes you are adding for the e2e tests, you might have a better luck with https://github.com/oliviertassinari/babel-plugin-react-remove-properties.
